/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(libs.org.apache.commons.commons.lang3)
}

description = "04-java-concurrency-api"
