/*
 * Rewards calculator
 * API to show the rewards for customers based on recorded purchases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.assignment.rewards.api;

import com.example.assignment.rewards.model.ErrorResponse;
import com.example.assignment.rewards.model.Orders;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for OrdersApi
 */
@Ignore
public class OrdersApiTest {

    private final OrdersApi api = new OrdersApi();

    
    /**
     * Returns rewards by customer Id
     *
     * Returns rewards by customer Id
     */
    @Test
    public void getOrdersByCustomerIdTest()  {
        String customerId = null;
        Orders response = api.getOrdersByCustomerId(customerId).block();

        // TODO: test validations
    }
    
    /**
     * Returns rewards by customer Id
     *
     * Returns rewards by customer Id
     */
    @Test
    public void postOrdersByCustomerIdTest()  {
        String customerId = null;
        Orders response = api.postOrdersByCustomerId(customerId).block();

        // TODO: test validations
    }
    
}
