/*
 * Rewards calculator
 * API to show the rewards for customers based on recorded purchases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.assignment.rewards.api;

import com.example.assignment.rewards.model.ErrorResponse;
import com.example.assignment.rewards.model.Rewards;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for RewardsApi
 */
@Ignore
public class RewardsApiTest {

    private final RewardsApi api = new RewardsApi();

    
    /**
     * Returns rewards by customer Id
     *
     * Returns rewards by customer Id
     */
    @Test
    public void getRewardsByCustomerIdTest()  {
        String customerId = null;
        Rewards response = api.getRewardsByCustomerId(customerId).block();

        // TODO: test validations
    }
    
    /**
     * Returns rewards by customer Id
     *
     * Returns rewards by customer Id
     */
    @Test
    public void postRewardsByCustomerIdTest()  {
        String customerId = null;
        Rewards response = api.postRewardsByCustomerId(customerId).block();

        // TODO: test validations
    }
    
}
