package com.example.springcloudawsdynamodb.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.springcloudawsdynamodb.entities.converter.SubObjectConverter;
import lombok.Data;
import org.springframework.data.annotation.Id;

import java.util.Date;

@Data
@DynamoDBTable(tableName = "ProductInfo")
// The tablename here is an identifier only.
// The real table comes from properties file.
// See Config#dynamoDBMapperConfig()
public class ProductInfoEntity {
    @Id
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "msrp")
    private String msrp;

    @DynamoDBAttribute(attributeName = "cost")
    private String cost;

    @DynamoDBAttribute(attributeName = "created_date_time")
    @DynamoDBAutoGeneratedTimestamp
    private Date createdDateTime;

    @DynamoDBAttribute(attributeName = "can_be_sold")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
    private Boolean canBeSold;

    @DynamoDBAttribute(attributeName = "sub_object")
    @DynamoDBTypeConverted(converter = SubObjectConverter.class)
    private SubObject subObject;
}
