// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Albums API
 *
 * This service provides API to manage albums.
 *
 * API version: v1.0.0
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	AlbumAPIService := openapi.NewAlbumAPIService()
	AlbumAPIController := openapi.NewAlbumAPIController(AlbumAPIService)

	router := openapi.NewRouter(AlbumAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
