*** Configure Tooling

   #+BEGIN_EXAMPLE
   git config --global push.default simple
   git config --global user.name "Bruce Wayne"
   git config --global user.email explorer436@tutanota.com
   git config --global merge.conflictstyle diff3
   git config --system core.longpaths true
   git config --global color.ui auto
   git config --global core.autocrlf true
   #+END_EXAMPLE

What is "merge.conflictStyle"? Specify the style in which conflicted hunks are written out to working tree files upon merge. The default is "merge", which shows a <<<<<<< conflict marker, changes made by one side, a ======= marker, changes made by the other side, and then a >>>>>>> marker. An alternate style, "diff3", adds a ||||||| marker and the original text before the ======= marker.

--------------------------------------------

*** Commands 

**** Create Repositories

| git init (project name) | Creates a new local repository with the specified name |
| git clone (url)         | downloads a project and its entire version history     |

--------------------------------------------

**** Create feature branch from command line

| git branch -vv                                                    | To find out which remote branch your local branch is tracking, command to give tracking branch                                                                                                           |
| git status -sb                                                    | To find out which remote branch your local branch is tracking, command to give tracking branch                                                                                                           |

| git remote update                                                 | command to update remote branches                                                                                                                                                                        |
| git remote update --prune                                         | command to update remote branches. This will remove all remote branches which you have a local record of, but are no longer actually present on the remote.                                              |

| git branch -m <newname>                                           | To rename the current local branch                                                                                                                                                                       |
| git branch (local branch name) -u (remote branch name)            | To point local branch to a different remote branch                                                                                                                                                       |
| git branch -a                                                     | command to list all branches                                                                                                                                                                             |
| git branch -r                                                     | Remote branches only.                                                                                                                                                                                    |
| git branch -l or `git branch`                                     | Local branches only.                                                                                                                                                                                     |

| git checkout -b feature/testFeatureBranch remotes/origin/develop` | To start a feature branch from command line, simply create a new branch from remotes/origin/develop                                                                                                     |
| git checkout localBranch1                                         | To find out which remote branch your local branch is tracking,                                                                                                                                           |
| git checkout localBranch2                                         | To find out which remote branch your local branch is tracking,                                                                                                                                           |

| git status                      | To see the status of the local repository                                                                                                                                                                                            |
| git diff filename.txt           | command to show changes in a specific file. command to see what you haven't "git add"ed yet                                                                                                                                          |
| git diff --word-diff myfile.txt | Instead of showing you two lines for each change, Git allows you to highlight changes in a line explicitly. (The result is usually colored nicely, the removed part being red and the added text green.)                             |
| git diff --cached myfile.txt    | command to see already "-add" ed changes                                                                                                                                                                                             |
| git add -A` or `git add .`      | To stage all changed files                                                                                                                                                                                                           |
| git add (fileName)`             | To stage individual changed files                                                                                                                                                                                                    |
| git checkout                    | To copy a file from some other commit to your current working tree. It doesn't automatically commit the file. (Switch branches or restore working tree files)                                                                        |
| git checkout fileName           | Command to undo changes to a single file in working directory                                                                                                                                                                        |
| git commit -m "commit message"  | To commit with a custom message                                                                                                                                                                                                      |
| git stash -u                    | command to undo all changes                                                                                                                                                                                                          |
| GIT LOG --ONELINE               | To view recent commit messages                                                                                                                                                                                                       |
| git push                        | To push the commits to an upsteam remote branch                                                                                                                                                                                      |
| git revert                      | To undo a previous commit. In git, you can't alter or erase an earlier commit. (Actually you can, but it can cause problems.) So instead of editing the earlier commit, revert introduces a new commit that reverses an earlier one. |

When doing a diff on a long line, this can be very helpful but you'll still get a less-like scrolling output that can be unhandy to use. You maybe just want the diff put into your terminal:

   #+BEGIN_EXAMPLE
   `PAGER='' git diff --word-diff myfile.txt`
   #+END_EXAMPLE

| git reset                                        | To undo changes in your working directory that haven't been comitted yet                                                                                                                                                                                                                                                                                                                                  |
| git reset --mixed HEAD file.txt                  | it essentially just takes whatever file.txt looks like in HEAD and puts that in the Index                                                                                                                                                                                                                                                                                                                 |
| git reset HEAD~                                  | If you do not want to push your commit to remote branch                                                                                                                                                                                                                                                                                                                                                   |
| git reset HEAD~                                  | To undo previous commits that you don't want to push                                                                                                                                                                                                                                                                                                                                                      |
| git reset --hard HEAD~                           | (You undid your last commit, all the git adds, and all the work you did in your working directory.)                                                                                                                                                                                                                                                                                                       |
| git reset --hard origin/master<remotebranchname> | master branch and 'origin/master' have diverged, how to 'undiverge' branches'                                                                                                                                                                                                                                                                                                                             |
| git reset --soft HEAD~                           | (When you reset back to HEAD~ (the parent of HEAD), you are moving the branch back to where it was without changing the Index (staging area) or Working Directory. You could now do a bit more work and commit again to accomplish basically what git commit --amend would have done. Note that if you run git status now you'll see in green the difference between the Index and what the new HEAD is.) |
| git reset --mixed HEAD~                          | It still undid your last commit, but also unstaged everything. You rolled back to before you ran all your git adds AND git commit.                                                                                                                                                                                                                                                                        |

| git clean                                                            | To remove local untracked files from the current Git branch                                    |
| git clean -n                                                         | To see which files will be deleted you can use the -n option before you run the actual command |
| git clean -f                                                         | When you are comfortable (because it will delete the files for real!) use the -f option        |
| git clean -f -d or git clean -fd                                     | To remove directories                                                                          |
| git clean -f -X or git clean -fX (Note the case difference on the X) | To remove ignored files                                                                        |
| git clean -f -x or git clean -fx (Note the case difference on the X) | To remove ignored and non-ignored files                                                        |

-------------------------------------------------------

GIT: SEE ALL UNPUSHED COMMITS OR COMMITS THAT ARE NOT IN ANOTHER BRANCH

| git cherry -v                   | If you need to find out which of your local commits are not on the remote server do this. The -v option prints out the commit messages. Without it you will see only the SHA1 codes.                   |
| git cherry -v origin/somebranch | You may also compare against another (upstream) branch like that. This tool is especially useful when you have a ton of commits after a merge and want to know the commit differences between branches |
| git show (COMMIT_HASH)          | Once you have the list from the command above, use this to see the files that changed in each commit                                                                                                   |

---------------------------------------------------
    
*** Undoing a git push

You need to make sure that no other users of this repository are fetching the incorrect changes or trying to build on top of the commits that you want removed because you are about to rewind history.

Then you need to 'force' push the old reference.

   #+BEGIN_EXAMPLE
   `git push -f origin last_known_good_commit:branch_name`
   #+END_EXAMPLE

e.g.

   #+BEGIN_EXAMPLE
   `git push -f origin cc4b63bebb6:alpha-0.3.0`
   #+END_EXAMPLE

------------------------------------------------

*** Undo a commit and redo

   #+BEGIN_EXAMPLE
    $ git commit -m "Something terribly misguided"              (1)
    
    $ git reset HEAD~                                           (2)
    
    << edit files as necessary >>                               (3)
    
    $ git add ...                                               (4)
    
    $ git commit -c ORIG_HEAD                                   (5)
   #+END_EXAMPLE

1. This is what you want to undo
2. This leaves your working tree (the state of your files on disk) unchanged but undoes the commit and leaves the changes you  committed unstaged (so they'll appear as "Changes not staged for commit" in git status, and you'll need to add them again before committing). If you only want to add more changes to the previous commit, or change the commit message1, you could use git reset --soft HEAD~ instead, which is like git reset HEAD~ (where HEAD~ is the same as HEAD~1) but leaves your existing changes staged.
3. Make corrections to working tree files.
4. git add anything that you want to include in your new commit.
5. Commit the changes, reusing the old commit message. reset copied the old head to .git/ORIG_HEAD; commit with -c ORIG_HEAD will open an editor, which initially contains the log message from the old commit and allows you to edit it. If you do not need to edit the message, you could use the -C option.

-------------------------------------------------------

If the commit you want to fix isn’t the most recent one:

   #+BEGIN_EXAMPLE
   git rebase --interactive $parent_of_flawed_commit (after the git log command, if you want to edit the fifth commit, then enter the name of the sixth commit in this command.)
   #+END_EXAMPLE
 
If you want to fix several flawed commits, pass the parent of the oldest one of them.

   #+BEGIN_EXAMPLE
   An editor will come up, with a list of all commits since the one you gave.
   Change pick to reword (or on old versions of Git, to edit) in front of any commits you want to fix.
   Once you save, Git will replay the listed commits.
   #+END_EXAMPLE
 
For each commit you want to reword, Git will drop you back into your editor. For each commit you want to edit, Git drops you into the shell. If you’re in the shell:

   #+BEGIN_EXAMPLE
   Change the commit in any way you like.
   git commit --amend
   git rebase --continue
   #+END_EXAMPLE

Most of this sequence will be explained to you by the output of the various commands as you go. It’s very easy, you don’t need to memorise it – just remember that git rebase --interactive lets you correct commits no matter how long ago they were.

-----------------------------------------------------------

*** Authentication issues

    If you need to set the username and password, use this command:
   #+BEGIN_EXAMPLE
   git remote set-url origin https://<username>:<password>@github.com/<details-about-the-repository>.git
   #+END_EXAMPLE

    $ git pull
    
    Permission denied (publickey).
    fatal: Could not read from remote repository.
    Please make sure you have the correct access rights and the repository exists.
    A "Permission denied" error means that the server rejected your connection. 
    
    Resolution 1 : 
   #+BEGIN_EXAMPLE
   git remote set-url origin https://n0281526@git.forge.lmig.com/scm/uscm-esales/services-policywriting.git
   #+END_EXAMPLE
    
    
    Resolution 2 : 
    
    If you generated the keys yourself from your client machine, do not forget to add them to the SSH agent using the command "ssh-add".
    Run ssh-add on the client machine, that will add the SSH key to the agent. 
    
    To figure out where your client's SSH agent is looking for private and public keys, use this command:
   #+BEGIN_EXAMPLE
   ssh -vT git@github.com
   #+END_EXAMPLE
    
    This will show the list of the directories that your computer's SSH agent is looking in for public and private keys.
    If everything looks good with this command, you are pretty much set to push and pull from the remote repositories.
    
    You can change the protocol that your local repository is using to communicate with the remote repository :
    It can be HTTPS or SSH.
    The issue with using HTTPS URL is, every time you want to push a change, it might ask you for username and password.
    With SSH, you don't have to enter username and password every single time.
    
    Use these commands to switch between the two :
    
    1. If you want to use HTTPS
    
      #+BEGIN_EXAMPLE
      git remote set-url origin https://github.com/USERNAME/REPOSITORY.git
      #+END_EXAMPLE

      If you got authentication issues with the GIT console you can try your auth this way:
      #+BEGIN_EXAMPLE
      https://<username>:<password>@bitbucket.org/<username>/<repo>.git
      #+END_EXAMPLE
    
    2. If you want to use SSH

      #+BEGIN_EXAMPLE
      git remote set-url origin git@github.com:USERNAME/REPOSITORY.git
      #+END_EXAMPLE

      And then run this:
      
      #+BEGIN_EXAMPLE
      ssh-keygen -t rsa -b 4096 -C "explorer436@tutanota.com"
      #+END_EXAMPLE

      (When you're prompted to "Enter a file in which to save the key," 
      press Enter. This accepts the default file location.) Now add this SSH ket to bitbucket server.
    
      If you want to add an SSH key generated from Git console to the ssh-agent in your computer : 

      You might need to start ssh-agent before you run the ssh-add command: 
      #+BEGIN_EXAMPLE
      eval `ssh-agent -s` or eval $(ssh-agent)
      #+END_EXAMPLE

      Add your SSH private key to the ssh-agent using the following command:
      #+BEGIN_EXAMPLE
      ssh-add  ~/Downloads/CloudForgeGitSSHKeys/id_rsa
      #+END_EXAMPLE
      (this should point to the location of the private key file)

-----------------------------------------------------------

*** Helpful Resources
    
    https://www.atlassian.com/git/tutorials/merging-vs-rebasing 

