/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "my-implementations"

include(":object-oriented-and-system-design-examples")
include(":06-java-thread-synchronization")
include(":lru-cache-implementation")
include(":lfu-cache-implementation")
include(":01-creating-threads")
include(":04-java-concurrency-api")
include(":java-multithreading-and-concurrency-demo")
include(":download-images-from-urls")
include(":05-daemon-threads")
include(":my-java-solutions")
include(":vending-machine-design")
include(":02-executor-service")
include(":json-processing")

project(":06-java-thread-synchronization").projectDir = file("java-multithreading-and-concurrency-demo/06-java-thread-synchronization")
project(":lru-cache-implementation").projectDir = file("object-oriented-and-system-design-examples/lru-cache-implementation")
project(":lfu-cache-implementation").projectDir = file("object-oriented-and-system-design-examples/lfu-cache-implementation")
project(":01-creating-threads").projectDir = file("java-multithreading-and-concurrency-demo/01-creating-threads")
project(":04-java-concurrency-api").projectDir = file("java-multithreading-and-concurrency-demo/04-java-concurrency-api")
project(":05-daemon-threads").projectDir = file("java-multithreading-and-concurrency-demo/05-daemon-threads")
project(":vending-machine-design").projectDir = file("object-oriented-and-system-design-examples/vending-machine-design")
project(":02-executor-service").projectDir = file("java-multithreading-and-concurrency-demo/02-executor-service")
