/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "my-implementations"

include(":object-oriented-and-system-design-examples:lru-cache-implementation")
include(":object-oriented-and-system-design-examples:lfu-cache-implementation")
include(":object-oriented-and-system-design-examples:vending-machine-design")
include(":java-multithreading-and-concurrency-demo:01-creating-threads")
include(":java-multithreading-and-concurrency-demo:02-executor-service")
include(":java-multithreading-and-concurrency-demo:04-java-concurrency-api")
include(":java-multithreading-and-concurrency-demo:05-daemon-threads")
include(":java-multithreading-and-concurrency-demo:06-java-thread-synchronization")
include(":json-processing")
include (":design-pattern-examples")
include (":searching-and-sorting")
include (":process-api-demo")
include (":my-utilities")
include (":algorithms-and-datastructures")
include (":streams-api-demo")
include (":exception-handling")
include (":static-demo")
include (":dynamic-dispatch-demo")
include (":code-aesthetics")
include (":functional-interface-lambda-expressions-demo")
