/*
 * Rewards calculator
 * API to show the rewards for customers based on recorded purchases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.assignment.rewards.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Reward
 */
public class RewardTest {
    private final Reward model = new Reward();

    /**
     * Model tests for Reward
     */
    @Test
    public void testReward() {
        // TODO: test Reward
    }

    /**
     * Test the property 'rewardPoints'
     */
    @Test
    public void rewardPointsTest() {
        // TODO: test rewardPoints
    }

    /**
     * Test the property 'purchaseAmount'
     */
    @Test
    public void purchaseAmountTest() {
        // TODO: test purchaseAmount
    }

    /**
     * Test the property 'month'
     */
    @Test
    public void monthTest() {
        // TODO: test month
    }

}
