/*
 * Rewards calculator
 * API to show the rewards for customers based on recorded purchases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.assignment.rewards.model;

import com.example.assignment.rewards.model.Reward;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Rewards
 */
public class RewardsTest {
    private final Rewards model = new Rewards();

    /**
     * Model tests for Rewards
     */
    @Test
    public void testRewards() {
        // TODO: test Rewards
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'totalRewardPointsForPastThreeMonths'
     */
    @Test
    public void totalRewardPointsForPastThreeMonthsTest() {
        // TODO: test totalRewardPointsForPastThreeMonths
    }

    /**
     * Test the property 'totalPurchaseAmountForPastThreeMonths'
     */
    @Test
    public void totalPurchaseAmountForPastThreeMonthsTest() {
        // TODO: test totalPurchaseAmountForPastThreeMonths
    }

    /**
     * Test the property 'rewards'
     */
    @Test
    public void rewardsTest() {
        // TODO: test rewards
    }

}
