// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Albums API
 *
 * This service provides API to manage albums.
 *
 * API version: v1.0.0
 */

package openapi

import (
	"context"
	"net/http"
)



// AlbumAPIRouter defines the required methods for binding the api requests to a responses for the AlbumAPI
// The AlbumAPIRouter implementation should parse necessary information from the http request,
// pass the data to a AlbumAPIServicer to perform the required actions, then write the service results to the http response.
type AlbumAPIRouter interface { 
	GetAlbums(http.ResponseWriter, *http.Request)
	PostAlbums(http.ResponseWriter, *http.Request)
	GetAlbumByID(http.ResponseWriter, *http.Request)
}


// AlbumAPIServicer defines the api actions for the AlbumAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type AlbumAPIServicer interface { 
	GetAlbums(context.Context) (ImplResponse, error)
	PostAlbums(context.Context, Album) (ImplResponse, error)
	GetAlbumByID(context.Context, int32) (ImplResponse, error)
}
