// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Albums API
 *
 * This service provides API to manage albums.
 *
 * API version: v1.0.0
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// AlbumAPIService is a service that implements the logic for the AlbumAPIServicer
// This service should implement the business logic for every endpoint for the AlbumAPI API.
// Include any external packages or services that will be required by this service.
type AlbumAPIService struct {
}

// NewAlbumAPIService creates a default api service
func NewAlbumAPIService() *AlbumAPIService {
	return &AlbumAPIService{}
}

// GetAlbums - Get Albums
func (s *AlbumAPIService) GetAlbums(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetAlbums with the required logic for this service method.
	// Add api_album_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Album{}) or use other options such as http.Ok ...
	// return Response(200, []Album{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetAlbums method not implemented")
}

// PostAlbums - Post Albums
func (s *AlbumAPIService) PostAlbums(ctx context.Context, album Album) (ImplResponse, error) {
	// TODO - update PostAlbums with the required logic for this service method.
	// Add api_album_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Album{}) or use other options such as http.Ok ...
	// return Response(201, Album{}), nil

	// TODO: Uncomment the next line to return response Response(409, RestErrResponse{}) or use other options such as http.Ok ...
	// return Response(409, RestErrResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("PostAlbums method not implemented")
}

// GetAlbumByID - Get Album By ID
func (s *AlbumAPIService) GetAlbumByID(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update GetAlbumByID with the required logic for this service method.
	// Add api_album_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Album{}) or use other options such as http.Ok ...
	// return Response(200, Album{}), nil

	// TODO: Uncomment the next line to return response Response(404, RestErrResponse{}) or use other options such as http.Ok ...
	// return Response(404, RestErrResponse{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetAlbumByID method not implemented")
}
