// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Albums API
 *
 * This service provides API to manage albums.
 *
 * API version: v1.0.0
 */

package openapi




type RestErrResponse struct {

	// Application-specific error code.
	Code int32 `json:"code,omitempty"`

	// Application context.
	Context map[string]interface{} `json:"context,omitempty"`

	// Error message.
	Error string `json:"error,omitempty"`

	// Status text.
	Status string `json:"status,omitempty"`
}

// AssertRestErrResponseRequired checks if the required fields are not zero-ed
func AssertRestErrResponseRequired(obj RestErrResponse) error {
	return nil
}

// AssertRestErrResponseConstraints checks if the values respects the defined constraints
func AssertRestErrResponseConstraints(obj RestErrResponse) error {
	return nil
}
