/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.spring.core)
    api(libs.org.springframework.spring.context)
    compileOnly(libs.org.projectlombok.lombok)
}

group = "com.example"
description = "02-executor-service"
