/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.spring.core)
    api(libs.org.springframework.spring.context)
}

description = "02-executor-service"
