/*
 * Rewards calculator
 * API to show the rewards for customers based on recorded purchases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.assignment.rewards.client;

import com.example.assignment.rewards.client.ApiException;
import com.example.assignment.rewards.model.Orders;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrdersApi
 */
@Disabled
public class OrdersApiTest {

    private final OrdersApi api = new OrdersApi();

    /**
     * Returns rewards by customer Id
     *
     * Returns rewards by customer Id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getOrdersByCustomerIdTest() throws ApiException {
        String customerId = null;
        Orders response = api.getOrdersByCustomerId(customerId);
        // TODO: test validations
    }

    /**
     * Returns rewards by customer Id
     *
     * Returns rewards by customer Id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postOrdersByCustomerIdTest() throws ApiException {
        String customerId = null;
        Orders response = api.postOrdersByCustomerId(customerId);
        // TODO: test validations
    }

}
