/*
 * Rewards calculator
 * API to show the rewards for customers based on recorded purchases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.assignment.rewards.client;

import com.example.assignment.rewards.client.ApiException;
import com.example.assignment.rewards.model.Rewards;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RewardsApi
 */
@Disabled
public class RewardsApiTest {

    private final RewardsApi api = new RewardsApi();

    /**
     * Returns rewards by customer Id
     *
     * Returns rewards by customer Id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRewardsByCustomerIdTest() throws ApiException {
        String customerId = null;
        Rewards response = api.getRewardsByCustomerId(customerId);
        // TODO: test validations
    }

    /**
     * Returns rewards by customer Id
     *
     * Returns rewards by customer Id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postRewardsByCustomerIdTest() throws ApiException {
        String customerId = null;
        Rewards response = api.postRewardsByCustomerId(customerId);
        // TODO: test validations
    }

}
