spring:
  cloud:
    stream:
      function:
        bindings:
          process-in-0: input
      bindings:
        input:
          destination: usage-cost

# spring.cloud.stream.function.bindings.process-in-0=input
# spring.cloud.stream.bindings.input.destination=usage-cost

# The spring.cloud.stream.function.bindings.process-in-0 property overrides the binding name to input and spring.cloud.stream.bindings.input.destinationproperty sets the destination to theusage-cost` Kafka topic.

server:
  port : 9003
