/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("io.freefair.lombok") version "8.14"
}

dependencies {
    api(libs.org.apache.commons.commons.collections4)
    api(libs.org.apache.commons.commons.lang3)
    api(libs.org.apache.commons.commons.exec)
    api(libs.org.slf4j.slf4j.simple)
    api(libs.com.google.guava.guava)
    api(libs.com.github.javafaker.javafaker)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.com.fasterxml.jackson.core.jackson.databind)
}

description = "my-java-solutions"
