* How to set JAVA_HOME in Linux for all users

** How to find out where Java is installed?

If Java is installed using package managers or by using any other ways other than downloading the JDK from https://openjdk.java.net/install/ , it can get tricky to find out where it is installed.

Here is one way to find it.

#+begin_src 
find /usr/lib/jvm/java-1.x.x-openjdk
#+end_src

** Download Java from openjdk website

A more straight-forward way is to download it from openjdk install page and extracting it using the command:
#+begin_src 
$ tar xvf openjdk-13*_bin.tar.gz
#+end_src

** How to set JAVA_HOME after figuring out where the jdk is?
#+begin_src 
vim /etc/profile
#+end_src

Prepend sudo if logged in as not-privileged user, ie. sudo vim

Press 'i' to get in insert mode and add this to the file:

#+begin_src 
export JAVA_HOME="path that you found"
export PATH=$JAVA_HOME/bin:$PATH
#+end_src

logout and login again, reboot, or use source /etc/profile to apply changes immediately in your current shell 

* Checking JAVA_HOME on Linux

Open a terminal and type:
#+begin_src 
> $JAVA_HOME/bin/javac -version
#+end_src

If JAVA_HOME points to a JDK, the output should look like:
#+begin_src 
> javac 1.X.0_XX
#+end_src

If JAVA_HOME doesn't point to a JDK, the OS will throw an error message:
#+begin_src 
> bash: /bin/javac: No such file or directory
#+end_src
