/*
 * Rewards calculator
 * API to show the rewards for customers based on recorded purchases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.assignment.rewards.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Order
 */
public class OrderTest {
    private final Order model = new Order();

    /**
     * Model tests for Order
     */
    @Test
    public void testOrder() {
        // TODO: test Order
    }

    /**
     * Test the property 'purchaseAmount'
     */
    @Test
    public void purchaseAmountTest() {
        // TODO: test purchaseAmount
    }

    /**
     * Test the property 'itemName'
     */
    @Test
    public void itemNameTest() {
        // TODO: test itemName
    }

    /**
     * Test the property 'itemDescription'
     */
    @Test
    public void itemDescriptionTest() {
        // TODO: test itemDescription
    }

}
