/*
 * Rewards calculator
 * API to show the rewards for customers based on recorded purchases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.assignment.rewards.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Reward
 */
public class RewardTest {
    private final Reward model = new Reward();

    /**
     * Model tests for Reward
     */
    @Test
    public void testReward() {
        // TODO: test Reward
    }

    /**
     * Test the property 'rewardPoints'
     */
    @Test
    public void rewardPointsTest() {
        // TODO: test rewardPoints
    }

    /**
     * Test the property 'purchaseAmount'
     */
    @Test
    public void purchaseAmountTest() {
        // TODO: test purchaseAmount
    }

    /**
     * Test the property 'month'
     */
    @Test
    public void monthTest() {
        // TODO: test month
    }

}
