/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
}

description = "lru-cache-implementation"
