/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.apache.commons.commons.lang3)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
}

description = "lfu-cache-implementation"
