/*
 * Rewards calculator
 * API to show the rewards for customers based on recorded purchases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.assignment.rewards.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Reward
 */
@JsonPropertyOrder({
  Reward.JSON_PROPERTY_REWARD_POINTS,
  Reward.JSON_PROPERTY_PURCHASE_AMOUNT,
  Reward.JSON_PROPERTY_MONTH
})
@lombok.Builder
@lombok.Getter
@lombok.extern.jackson.Jacksonized
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Reward implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_REWARD_POINTS = "rewardPoints";
  private Integer rewardPoints;

  public static final String JSON_PROPERTY_PURCHASE_AMOUNT = "purchaseAmount";
  private Double purchaseAmount;

  public static final String JSON_PROPERTY_MONTH = "month";
  private String month;

  public Reward() { 
  }

  public Reward rewardPoints(Integer rewardPoints) {
    
    this.rewardPoints = rewardPoints;
    return this;
  }

   /**
   * Get rewardPoints
   * @return rewardPoints
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REWARD_POINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRewardPoints() {
    return rewardPoints;
  }


  @JsonProperty(JSON_PROPERTY_REWARD_POINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRewardPoints(Integer rewardPoints) {
    this.rewardPoints = rewardPoints;
  }


  public Reward purchaseAmount(Double purchaseAmount) {
    
    this.purchaseAmount = purchaseAmount;
    return this;
  }

   /**
   * Get purchaseAmount
   * @return purchaseAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PURCHASE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPurchaseAmount() {
    return purchaseAmount;
  }


  @JsonProperty(JSON_PROPERTY_PURCHASE_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPurchaseAmount(Double purchaseAmount) {
    this.purchaseAmount = purchaseAmount;
  }


  public Reward month(String month) {
    
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MONTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMonth() {
    return month;
  }


  @JsonProperty(JSON_PROPERTY_MONTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMonth(String month) {
    this.month = month;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Reward reward = (Reward) o;
    return Objects.equals(this.rewardPoints, reward.rewardPoints) &&
        Objects.equals(this.purchaseAmount, reward.purchaseAmount) &&
        Objects.equals(this.month, reward.month);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rewardPoints, purchaseAmount, month);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Reward {\n");
    sb.append("    rewardPoints: ").append(toIndentedString(rewardPoints)).append("\n");
    sb.append("    purchaseAmount: ").append(toIndentedString(purchaseAmount)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

