/*
 * Rewards calculator
 * API to show the rewards for customers based on recorded purchases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.assignment.rewards.model;

import java.util.Objects;
import java.util.Arrays;
import com.example.assignment.rewards.model.Reward;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Rewards
 */
@JsonPropertyOrder({
  Rewards.JSON_PROPERTY_CUSTOMER_ID,
  Rewards.JSON_PROPERTY_TOTAL_REWARD_POINTS_FOR_PAST_THREE_MONTHS,
  Rewards.JSON_PROPERTY_TOTAL_PURCHASE_AMOUNT_FOR_PAST_THREE_MONTHS,
  Rewards.JSON_PROPERTY_REWARDS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Rewards implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CUSTOMER_ID = "customerId";
  private String customerId;

  public static final String JSON_PROPERTY_TOTAL_REWARD_POINTS_FOR_PAST_THREE_MONTHS = "totalRewardPointsForPastThreeMonths";
  private Integer totalRewardPointsForPastThreeMonths;

  public static final String JSON_PROPERTY_TOTAL_PURCHASE_AMOUNT_FOR_PAST_THREE_MONTHS = "totalPurchaseAmountForPastThreeMonths";
  private Double totalPurchaseAmountForPastThreeMonths;

  public static final String JSON_PROPERTY_REWARDS = "rewards";
  private List<Reward> rewards;

  public Rewards() {
  }

  public Rewards customerId(String customerId) {
    
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCustomerId() {
    return customerId;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }


  public Rewards totalRewardPointsForPastThreeMonths(Integer totalRewardPointsForPastThreeMonths) {
    
    this.totalRewardPointsForPastThreeMonths = totalRewardPointsForPastThreeMonths;
    return this;
  }

   /**
   * Get totalRewardPointsForPastThreeMonths
   * @return totalRewardPointsForPastThreeMonths
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_REWARD_POINTS_FOR_PAST_THREE_MONTHS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalRewardPointsForPastThreeMonths() {
    return totalRewardPointsForPastThreeMonths;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_REWARD_POINTS_FOR_PAST_THREE_MONTHS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalRewardPointsForPastThreeMonths(Integer totalRewardPointsForPastThreeMonths) {
    this.totalRewardPointsForPastThreeMonths = totalRewardPointsForPastThreeMonths;
  }


  public Rewards totalPurchaseAmountForPastThreeMonths(Double totalPurchaseAmountForPastThreeMonths) {
    
    this.totalPurchaseAmountForPastThreeMonths = totalPurchaseAmountForPastThreeMonths;
    return this;
  }

   /**
   * Get totalPurchaseAmountForPastThreeMonths
   * @return totalPurchaseAmountForPastThreeMonths
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_PURCHASE_AMOUNT_FOR_PAST_THREE_MONTHS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTotalPurchaseAmountForPastThreeMonths() {
    return totalPurchaseAmountForPastThreeMonths;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_PURCHASE_AMOUNT_FOR_PAST_THREE_MONTHS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalPurchaseAmountForPastThreeMonths(Double totalPurchaseAmountForPastThreeMonths) {
    this.totalPurchaseAmountForPastThreeMonths = totalPurchaseAmountForPastThreeMonths;
  }


  public Rewards rewards(List<Reward> rewards) {
    
    this.rewards = rewards;
    return this;
  }

  public Rewards addRewardsItem(Reward rewardsItem) {
    if (this.rewards == null) {
      this.rewards = new ArrayList<>();
    }
    this.rewards.add(rewardsItem);
    return this;
  }

   /**
   * Get rewards
   * @return rewards
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REWARDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Reward> getRewards() {
    return rewards;
  }


  @JsonProperty(JSON_PROPERTY_REWARDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRewards(List<Reward> rewards) {
    this.rewards = rewards;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rewards rewards = (Rewards) o;
    return Objects.equals(this.customerId, rewards.customerId) &&
        Objects.equals(this.totalRewardPointsForPastThreeMonths, rewards.totalRewardPointsForPastThreeMonths) &&
        Objects.equals(this.totalPurchaseAmountForPastThreeMonths, rewards.totalPurchaseAmountForPastThreeMonths) &&
        Objects.equals(this.rewards, rewards.rewards);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, totalRewardPointsForPastThreeMonths, totalPurchaseAmountForPastThreeMonths, rewards);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rewards {\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    totalRewardPointsForPastThreeMonths: ").append(toIndentedString(totalRewardPointsForPastThreeMonths)).append("\n");
    sb.append("    totalPurchaseAmountForPastThreeMonths: ").append(toIndentedString(totalPurchaseAmountForPastThreeMonths)).append("\n");
    sb.append("    rewards: ").append(toIndentedString(rewards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

