# https://hub.docker.com/r/wurstmeister/kafka
# https://wurstmeister.github.io/kafka-docker/
#
# Command to spin up the containers
# $docker-compose --file docker-compose-wurstmeister.yml up -d 
---
version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
