spring:
  cloud:
    function:
      definition: consumer10;producer6
    stream:
      bindings:
        consumer10-in-0:
          destination: input-topic
          group: some-group
        producer6-out-0:
          destination: input-topic
      # reactor.core.Exceptions$ErrorCallbackNotImplemented: org.apache.kafka.common.errors.SerializationException: Can't convert key of class java.lang.String to class org.apache.kafka.common.serialization.ByteArraySerializer specified in key.serializer
      # Caused by: org.apache.kafka.common.errors.SerializationException: Can't convert key of class java.lang.String to class org.apache.kafka.common.serialization.ByteArraySerializer specified in key.serializer
      # We have to specify the type of Serializer and Deserializer for headers
      # By default, spring expects ByteArraySerializer and not Strings
      kafka:
        binder:
          producer-properties:
            "key.serializer": org.apache.kafka.common.serialization.StringSerializer
          consumer-properties:
            "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
            "auto.offset.reset": "earliest"
            "group.instance.id": "1"
