/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(libs.org.apache.commons.commons.exec)
    implementation(libs.org.slf4j.slf4j.simple)
}

description = "process-api-demo"
