/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.spring.context)
    testImplementation(libs.junit.junit)
}

description = "01-creating-threads"
