/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    implementation(libs.com.github.javafaker.javafaker)
    implementation(libs.com.google.guava.guava)
}

description = "code-aesthetics"
