[package]
name = "hello_world_using_cargo"
version = "0.1.0"
edition = "2021"
# edition of Rust to use

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
