/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.apache.commons.commons.lang3.x1)
    // JUnit Jupiter API for writing tests
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.0")
    // JUnit Jupiter Engine for running tests
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.11.0")
    // JUnit Platform Launcher (for running tests, often implicitly added by Gradle with test suites)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.11.0")
}

tasks.test {
    useJUnitPlatform {
        version = "5.8.2"
    }
}

description = "vending-machine-design"