/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.apache.commons.commons.lang3.x1)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
}

description = "vending-machine-design"
