* Auto-healer using Zookeeper

1. In cloud computing, auto-healing is a feature used to monitor a cluster and detect faulty application instances.
2. If a faulty instance is detected, the node is shut down and a new node is created with a healthy application instance.
3. In this practical assignment we will implement a very basic auto healer which will monitor a group of worker instances.

* Problem

1. You are given a worker application
2. The worker instances are running a very complex computation that tends to crash in a particular edge case that the author did not account for.
3. Our mission is to maintain at least N worker nodes at any given moment.
4. If a worker crashes, we need to start a new worker.

* Instructions

1. The flaky worker. This is a program that emulates a worker that randomly dies due to an exception
2. The Auto-healer. This is only a partially complete project, your task is to complete the unimplemented methods
3. Once the implementation is complete.

Run Zookeeper by running the zkServer.XX start command in the bin directory

Build the worker project using the  mvn clean install command

Following the Autohealer README for building and running the autohealer to launch and maintain any number of workers