/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.apache.commons.commons.lang3)
    testImplementation(libs.junit.junit)
}

description = "download-images-from-urls"
