* Gradle                                                              :TOC_9:
- [[#issues-with-refreshing-dependencies-in-eclipse][Issues with refreshing dependencies in Eclipse]]
- [[#helpful-gradle-commands][Helpful Gradle commands]]
    - [[#list-all-tasks][List all tasks]]
    - [[#publish-to-maven-local][Publish to maven local]]
    - [[#working-with-ear-projects][Working with EAR projects]]
- [[#how-to-exclude-a-few-tasks-from-the-gradle-build-process-][How to exclude a few tasks from the Gradle build process :]]

* Issues with refreshing dependencies in Eclipse

If there is trouble refreshing the dependencies in Eclipse after making changes to the build.gradle file, follow the steps below:

1. check if you have included eclipse gradle plugin. `apply plugin : 'eclipse'`
1. Go to your project terminal
1. Run `gradle tasks --all` to see the list of all available gradle tasks.
1. If the task `cleanEclipse` is available, run it.
1. If not, run `gradle cleanEclipseProject` and `gradle cleanEclipseClasspath` separately.
1. After that, run `gradle eclipse`
1. Go to the project in eclipse and refresh the project.

This should bring all the latest dependencies down and you should see them in the `Referenced Libraries` section.

* Helpful Gradle commands

*** List all tasks

To look at all the available tasks for a gradle project, use this: 

#+begin_src 
gradlew tasks --all  
#+end_src

*** Publish to maven local

`gradlew publishToMavenLocal`

*** Working with EAR projects

Go to the EAR folder in command prompt:

    #+begin_src 
    C:\XXXXXXXXXXXXXEAR
    #+end_src

And use this command to build EAR.

    #+begin_src 
    gradle clean ear --info
    gradle clean testall --info
    gradle clean testAll ear –-info
    #+end_src

From folder :      ~C:\XXXXXXXXXXEAR\build\distributions~
To folder :        ~C:\WASLP_dev\tools\WASLP8559\wlp\usr\servers\default\dropins~

Windows command to copy the EAR from a source folder to a destination folder:
    #+begin_src 
    xcopy C:\XXXXXXXXXXXXXXEAR\build\distributions C:\WASLP_dev\tools\WASLP8559\wlp\usr\servers\default\dropins
    #+end_src

From folder :      ~C:\Users\n0281526\Documents\services-property-insurance-partner-exchange\PiAcordSalesMediationServiceEAR~
To folder :        ~C:\WASLP_dev\tools\WASLP8559\wlp\usr\servers\default\dropins~

Windows command to copy the EAR from a source folder to a destination folder:
    #+begin_src 
    xcopy C:\WASLP_dev\workspaces\git_repo\services-property-insurance-partner-exchange\PiAcordSalesMediationServiceEAR\build\distributions     C:\WASLP_dev\tools\WASLP8559\wlp\usr\servers\default\dropins
    #+end_src

* How to exclude a few tasks from the Gradle build process :
  #+begin_src 
  ./gradlew build -x checkstyleMain -x findbugsMain -x test -x jacocoTestCoverageVerification -x pmdMain
  #+end_src
