* Maven Installation details

    Prerequisites: jdk

    See JavaInstallation.org for details about installing jdk

*** Step 1: Download the Maven Binaries

    Go to the URL: https://maven.apache.org/download.cgi Copy the link for the “Binary tar.gz archive” file.

    Then run the following commands to download and untar it.

    #+begin_src 
    $ tar -xvf apache-maven-3.6.3-bin.tar.gz
    #+end_src

*** Step 2: Setting M2_HOME and Path Variables

    See LinuxTips.org and then use the same pattern to add maven bin folder to PATH in .bashrc file.

    See SettingJavaHomeInLinux.org and then use the same pattern to add maven bin folder to PATH.

    Use ~.bashrc~ for Linux computers and ~.zshrc~ for Macbooks.

    https://maven.apache.org/install.html

    Add the following lines to .bashrc or .zshrc

    #+begin_src 
    export M2_HOME=/home/h/Documents/apache-maven-3.8.6
    export PATH=$M2_HOME/bin:$PATH
    #+end_src

    Relaunch the terminal or execute source .profile to apply the changes.    

*** Step 3: Verify the Maven installation

    Execute ~mvn -version~ command and it should produce the following output.

    #+begin_src 
    [h@h-p50-20eqs27p03 ~]$ mvn -version
    Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
    Maven home: /home/h/Documents/apache-maven-3.8.6
    Java version: 18, vendor: Oracle Corporation, runtime: /home/h/Downloads/jdk-18
    Default locale: en_US, platform encoding: UTF-8
    OS name: "linux", version: "5.19.11-arch1-1", arch: "amd64", family: "unix"
    #+end_src
