* Helpful curl commands

** References

https://curl.se/docs/

https://everything.curl.dev/http

In every HTTP request, there is a method. Sometimes called a verb. The most commonly used ones are GET, POST, HEAD and PUT.

Normally however you do not specify the method in the command line, but instead the exact method used depends on the specific options you use. GET is default, using -d or -F makes it a POST, -I generates a HEAD and -T sends a PUT.

** POST
#+begin_src 
curl -X POST -H "Content-Type: application/json" -d '{"name": "linuxize", "email": "linuxize@example.com"}'  https://endpoint.com
#+end_src

https://everything.curl.dev/http/post

** PUT

https://everything.curl.dev/http/put

** Display headers

We can use ~curl -v~ or ~curl -verbose~ to display the request headers and response headers in the cURL command.

In the cURL response

The > lines are request headers.
The < lines are response headers.

    Example:
    #+begin_src 
    [h@h-p50-20eqs27p03 springboot-mongodb-crud-rest-api]$ curl -v http://localhost:8080/users
    *   Trying 127.0.0.1:8080...
    * Connected to localhost (127.0.0.1) port 8080 (#0)
    > GET /users HTTP/1.1
    > Host: localhost:8080
    > User-Agent: curl/7.85.0
    > Accept: */*
    > 
    * Mark bundle as not supporting multiuse
    < HTTP/1.1 200 
    < Content-Type: application/json
    < Transfer-Encoding: chunked
    < Date: Wed, 19 Oct 2022 03:25:02 GMT
    < 
    * Connection #0 to host localhost left intact
        [{"id":"634f6c60e5d2eb3a186b05d3","username":"myself","correctAnswer":"right","numberOfTries":0,"attemptedWords":null},{"id":"634f6de9e5d2eb3a186b05d4","username":"myself","correctAnswer":null,"numberOfTries":0,"attemptedWords":null}]  
    #+end_src

** How to Pretty Print JSON output in cURL

In cURL requests, the default JSON output is in compact format.

In cURL, we can use or pipe the json_pp to pretty print the JSON output.

#+begin_src 
curl https://api.cloudflare.com/client/v4/ -verbose | json_pp  
#+end_src

