/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    testImplementation(libs.junit.junit)
}

description = "06-java-thread-synchronization"
